# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

- title: Automatic Construction of Nonparametric Relational Regression Models for Multiple Time Series
  authors:
    - Yunseong Hwang
    - Anh Tong
    - Jaesik Choi
  publisher: International Conference on Machine Learning (ICML)
  date: 2016-01-01
  link: http://proceedings.mlr.press/v48/hwangb16.pdf

- title: Discovering Latent Covariance Structures for Multiple Time Series
  authors:
    - Anh Tong
    - Jaesik Choi
  publisher: International Conference on Machine Learning (ICML)
  date: 2019-01-01
  link: http://proceedings.mlr.press/v97/tong19a/tong19a.pdf

- title: Confirmatory Bayesian online change point detection in the covariance structure of Gaussian processes
  authors: 
    - Jiyeon Han
    - Kyowoon Lee
    - Anh Tong
    - Jaesik Choi
  publisher:  International Joint Conference on Artificial Intelligence (IJCAI)
  date: 2019-01-01
  link: https://www.ijcai.org/Proceedings/2019/0340.pdf

- title: Learning fractional white noises in neural stochastic differential equations
  authors:
    - Anh Tong
    - Thanh Nguyen-Tang
    - Toan Tran
    - Jaesik Choi
  publisher: Advances in Neural Information Processing Systems (NeurIPS)
  date: 2022-12-01
  link: https://proceedings.neurips.cc/paper_files/paper/2022/file/f51df088779c27cbb25b8f094a346544-Paper-Conference.pdf

- title: Learning Compositional Sparse Gaussian Processes with a Shrinkage Prior
  authors:
    - Anh Tong
    - Toan Tran
    - Hung Bui
    - Jaesik Choi
  publisher: AAAI Conference on Artificial Intelligence (AAAI)
  date: 2021-01-01
  link: https://ojs.aaai.org/index.php/AAAI/article/download/17190/16997

- title: Characterizing Deep Gaussian Processes via Nonlinear Recurrence Systems
  authors:
    - Anh Tong
    - Jaesik Choi
  publisher: AAAI Conference on Artificial Intelligence (AAAI)
  date: 2021-01-01
  link: https://ojs.aaai.org/index.php/AAAI/article/view/17191/16998

- id: doi:10.1007/s11356-023-29036-0

- title: Global Contrastive Learning for Long-Tailed Classification
  authors:
    - Thong Bach
    - Anh Tong
    - Truong Hy Son
    - Vu Nguyen
    - Thanh Nguyen-Tang
  publisher: Transactions on Machine Learning Research (TMLR)
  date: 2023-01-01
  link: https://openreview.net/pdf?id=xWrtiJwJj5